sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install flake8 pylint aiohttp
language: python
script:
- flake8 ambiclimate --max-line-length=120
- pylint ambiclimate --max-line-length=120
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: gXsYee5E7n7E2djQJ+Do4LdMKwf1+uYe5aApaUUk6sqEbTuaDyGIN3UaSHM5lT2DKRPlwOGXrrUtdBabPafBXdkPSNPOdmyfsmuXuMBK9TeKMVjMqWN/j2RfMWwMYK4dIoxpO1OEE2FuhtlnAk2xkc1sudMDZIaEuCgy3seCLzOQJxxs2Enp7Tkh5YgkYMuS4s2TyNmYnGwDFNu3IoOhMW/RbMnYViyApdUqoFGdO2LMz5yxI2sHZ9xF7jd7dNi74swv7aLou/n8WrsDzByQpDDQi/OlbRthNRJmx7EFNdCfeqvTTYB4vjrZZoCFSg6FllKUS8BjBwdYx5bz+dPd8g/C2sWB37emIdv+EOrbANQsu2I5jbDBqKXTZlaYJ1qbJdhTyuUdlPhsMXNivjkuSYZ+fGv8DQiXxr1L0T2jjI5WrftWJWI7AJK8YUFx/miY6J5mcKX+uTT5RRwFdggr8e68WdgwzQZEgxO1lP/4uDmjUujfFz9N/YX6nUIVXpGjZ/uyD3OqYt9K78uDvBAryGsXv9IcJld1736P64T1COaLl1cihwEK37lp697ENVcmpi9LQY0limu7uRGJsq2SpAwcst9a+Lcqy8jJpINELTGmTBxI00k/tJraHmZE3BU5QT0eTnDbPr7TTfirTby1EksXCyKPgIRFxQZNmV1UbKA=
  on:
    tags: true
    repo: Danielhiversen/pyAmbiclimate
    branch: master
